### ISSUE TITLE
2010 Agile to 2013 Scrum upgrade results in error: Could not import work item type definition 'Code Review Request'

### ISSUE THREAD

**Issue by jzajac2** [jstangroome/WitMorph#23]
Log file shows:  IMPORT: TF26177: The field System.IterationId cannot be renamed from 'IterationID' to 'Iteration ID'. 

In the 'team project to convert to a new process', my User Story WIT has name="IterationID" refname="System.IterationId". This is from the TFS 2010 Agile process template.

In the "Process to convert to", my Product Backlog Item WIT has a space: name="Iteration ID" refname="System.IterationId". This is from the Scrum 2.0 process template.

I am using the Agile6ToScrum2.witmap, however has also tried the Agile6.1_to_Scrum2.1.witmap and got same result

Is there something wrong with my setup? My understanding was that WitMorph would do the field renaming for me, in this case for the User Story -> Product Backlog Item morph, or do I have to do that myself, first?

**Comment by jessehouwing** [comment]
Fixed in: #25
